import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from 'react'

export type Locale = 'en' | 'zh'
type Params = Record<string, string | number>

const en: Record<string, string> = {
  'language.label': 'Language', 'language.en': 'English', 'language.zh': '中文',
  'shell.tagline': 'Persistence first', 'shell.overview': 'Overview', 'shell.definitions': 'Definitions', 'shell.instances': 'Instances', 'shell.tasks': 'Human tasks', 'shell.workers': 'Worker lab', 'shell.deadLetters': 'Dead letters', 'shell.diagnostics': 'Diagnostics',
  'shell.online': 'Engine online', 'shell.offline': 'Engine offline', 'shell.checking': 'Checking engine', 'shell.tenant': 'Tenant', 'shell.default': 'default', 'shell.apiKey': 'API key', 'shell.optional': 'optional', 'shell.save': 'Save connection',
  'common.refresh': 'Refresh', 'common.delete': 'Delete', 'common.none': 'None', 'common.instance': 'Instance', 'common.token': 'Token', 'common.tenant': 'Tenant', 'common.task': 'Task', 'common.status': 'Status', 'common.variables': 'Variables', 'common.required': 'required', 'common.select': 'Select…', 'common.true': 'True', 'common.false': 'False', 'common.default': 'default',
  'status.active': 'Active', 'status.deprecated': 'Deprecated', 'status.running': 'Running', 'status.completed': 'Completed', 'status.terminated': 'Terminated', 'status.waiting': 'Waiting', 'status.ready': 'Ready', 'status.executing': 'Executing', 'status.created': 'Created', 'status.suspended': 'Suspended', 'status.ok': 'OK', 'status.degraded': 'Degraded', 'status.critical': 'Critical', 'status.warning': 'Warning', 'status.info': 'Info', 'status.pass': 'Pass', 'status.fail': 'Fail',
  'home.eyebrow': 'Operations', 'home.title': 'Workflow control plane', 'home.description': 'One place to deploy, execute, inspect, and recover persistent workflows.', 'home.refresh': 'Refresh data',
  'home.definitions': 'Definitions', 'home.definitionHint': 'deployed versions', 'home.instances': 'Instances', 'home.instanceHint': 'all known executions', 'home.openTasks': 'Open tasks', 'home.taskHint': 'waiting for action', 'home.deadLetters': 'Dead letters', 'home.deadHint': 'requiring recovery',
  'home.readiness': 'Runtime readiness', 'home.readinessHint': 'Live component checks from the engine', 'home.serviceState': 'Current service state', 'home.unknown': 'unknown', 'home.invariants': 'Persistence invariants', 'home.invariantsHint': 'Consistency checks across durable engine state', 'home.allPassed': 'All checks passed', 'home.violations': '{count} violations', 'home.validationTime': '{ms} ms validation time', 'home.external': 'External',
  'home.quick': 'Quick actions', 'home.quickHint': 'Jump directly into common operating flows', 'home.deploy': 'Deploy BPMN', 'home.deployHint': 'Publish a new immutable process definition.', 'home.start': 'Start instance', 'home.startHint': 'Launch a workflow with runtime variables.', 'home.claim': 'Claim work', 'home.claimHint': 'Fetch and manage leased external tasks.',
  'definitions.eyebrow': 'Design registry', 'definitions.title': 'Process definitions', 'definitions.description': 'Deploy BPMN, manage immutable versions, and launch new executions.', 'definitions.registry': 'Definition registry', 'definitions.count': '{count} deployed versions', 'definitions.empty': 'No definitions', 'definitions.emptyHint': 'Deploy BPMN from the editor to get started.',
  'definitions.detail': 'Definition detail', 'definitions.select': 'Select a definition', 'definitions.created': 'Created {date}', 'definitions.deprecate': 'Deprecate', 'definitions.activate': 'Activate', 'definitions.nothing': 'Nothing selected', 'definitions.nothingHint': 'Choose a definition from the registry.', 'definitions.activeVersion': 'Active version', 'definitions.startNode': 'Start node', 'definitions.nodes': 'Nodes', 'definitions.edges': 'Edges', 'definitions.history': 'Version history', 'definitions.graph': 'Graph model', 'definitions.initialVariables': 'Initial variables', 'definitions.encrypted': 'Encrypted variable names', 'definitions.start': 'Start process instance', 'definitions.deployment': 'BPMN deployment', 'definitions.deploymentHint': 'Paste executable BPMN 2.0 XML. Deploying the same key creates version metadata.', 'definitions.characters': '{count} characters', 'definitions.deploy': 'Deploy definition', 'definitions.deployed': 'Deployed {id}', 'definitions.statusChanged': '{id} is now {status}',
  'instances.eyebrow': 'Execution inventory', 'instances.title': 'Process instances', 'instances.description': 'Launch workflows, find executions, and open their persisted trace.', 'instances.startTitle': 'Start a new instance', 'instances.startHint': 'Active definitions are available immediately after deployment.', 'instances.definition': 'Process definition', 'instances.start': 'Start instance', 'instances.lookup': 'Direct lookup', 'instances.lookupHint': 'Use an exact instance ID from logs or an external system.', 'instances.id': 'Instance ID', 'instances.load': 'Load instance', 'instances.inventory': 'Execution inventory', 'instances.matching': '{count} matching instances', 'instances.search': 'Search instances', 'instances.empty': 'No instances found', 'instances.emptyHint': 'Start a process instance or change the search query.', 'instances.definitionColumn': 'Definition', 'instances.currentNodes': 'Current nodes', 'instances.tokens': 'Tokens', 'instances.openTrace': 'Open trace →',
  'tasks.eyebrow': 'Human workflow', 'tasks.title': 'Task inbox', 'tasks.description': 'Inspect generated form schemas and complete user tasks with validated variables.', 'tasks.refresh': 'Refresh inbox', 'tasks.waiting': 'Waiting tasks', 'tasks.available': '{count} tasks available', 'tasks.empty': 'Inbox clear', 'tasks.emptyHint': 'There are no user tasks waiting for completion.', 'tasks.detail': 'Task detail', 'tasks.choose': 'Choose a task from the inbox', 'tasks.noSelection': 'No task selected', 'tasks.noSelectionHint': 'Select a task to load its BPMN form schema.', 'tasks.completeTitle': 'Complete {node}', 'tasks.formKey': 'Form key', 'tasks.inlineForm': 'Inline form', 'tasks.noFields': 'No structured form fields. Complete the task with an empty variables object.', 'tasks.complete': 'Complete task', 'tasks.completed': 'Task {id} completed',
  'workers.eyebrow': 'Lease simulator', 'workers.title': 'External worker lab', 'workers.description': 'Exercise fetch-and-lock semantics and manage task leases without running a separate SDK worker.', 'workers.subscription': 'Worker subscription', 'workers.subscriptionHint': 'Claim ready tasks by topic using an exclusive, time-bound lease.', 'workers.workerId': 'Worker ID', 'workers.topics': 'Topics', 'workers.maxTasks': 'Max tasks', 'workers.lockDuration': 'Lock duration (ms)', 'workers.fetch': 'Fetch and lock tasks', 'workers.leased': 'Leased work', 'workers.owned': '{count} tasks owned by {worker}', 'workers.empty': 'No leased tasks', 'workers.emptyHint': 'Fetch a topic to claim available external work.', 'workers.operation': 'Task operation', 'workers.select': 'Select a leased task', 'workers.noSelection': 'No task selected', 'workers.noSelectionHint': 'Select a task to complete, fail, or extend its lease.', 'workers.completionVariables': 'Completion variables', 'workers.failureMessage': 'Failure message', 'workers.extend': 'Extend lease', 'workers.fail': 'Fail task', 'workers.complete': 'Complete task', 'workers.inputVariables': 'Input variables', 'workers.locked': 'Locked {count} tasks', 'workers.actionResult': '{id} {action}', 'workers.action.extended': 'lock extended', 'workers.action.completed': 'completed', 'workers.action.failed': 'failed', 'workers.defaultError': 'Worker reported an error',
  'dead.eyebrow': 'Recovery queue', 'dead.title': 'Dead letters', 'dead.description': 'Inspect exhausted external tasks, requeue recoverable work, or remove obsolete records.', 'dead.refresh': 'Refresh queue', 'dead.failed': 'Failed work', 'dead.count': '{count} entries require attention', 'dead.empty': 'Queue is empty', 'dead.emptyHint': 'No external tasks have exhausted their retries.', 'dead.detail': 'Dead letter detail', 'dead.select': 'Select an entry', 'dead.requeue': 'Requeue task', 'dead.noSelection': 'No entry selected', 'dead.noSelectionHint': 'Choose a dead letter to inspect its failure context.', 'dead.persistedVariables': 'Persisted variables', 'dead.requeued': 'Requeued task {id}', 'dead.deleted': 'Dead letter deleted', 'dead.confirm': 'Delete dead letter {id}?',
  'diagnostics.eyebrow': 'Runtime assurance', 'diagnostics.title': 'Diagnostics', 'diagnostics.description': 'Probe service health and verify the formal persistence invariants enforced by the engine.', 'diagnostics.run': 'Run checks', 'diagnostics.liveness': 'Liveness', 'diagnostics.readiness': 'Readiness', 'diagnostics.result': 'Invariant result', 'diagnostics.violations': '{count} violations', 'diagnostics.latency': 'Check latency', 'diagnostics.scan': 'full persistence scan', 'diagnostics.readinessChecks': 'Readiness checks', 'diagnostics.readinessHint': 'Component-level availability reported by the REST server', 'diagnostics.entities': 'Checked entities', 'diagnostics.entitiesHint': 'Scope of the latest invariant scan', 'diagnostics.externalTasks': 'External tasks', 'diagnostics.timers': 'Timers', 'diagnostics.invariantViolations': 'Invariant violations', 'diagnostics.invariantHint': 'Critical findings indicate state corruption; warnings may affect execution correctness.', 'diagnostics.noViolations': 'No violations', 'diagnostics.noViolationsHint': 'All checked persistence invariants currently hold.', 'diagnostics.severity': 'Severity', 'diagnostics.invariant': 'Invariant', 'diagnostics.entity': 'Entity', 'diagnostics.details': 'Description',
  'trace.instances': 'Instances', 'trace.missing': 'Missing instance ID.', 'trace.return': 'Return to instances', 'trace.topology': 'Process topology', 'trace.topologyHint': 'Current token positions on the compiled definition', 'trace.history': 'Execution history', 'trace.historyHint': 'Causally ordered, filterable persisted events', 'trace.payload': 'Event payload', 'trace.payloadHint': 'Select a timeline record to inspect its persisted data', 'trace.replay': 'Deterministic replay', 'trace.replayHint': 'Rebuild state event-by-event in an isolated session', 'trace.createReplay': 'Create replay', 'trace.close': 'Close session', 'trace.timelineCount': '{count} token timelines', 'trace.createHint': 'Create an ephemeral replay session to step through {count} persisted events.', 'trace.back': 'Back', 'trace.step': 'Step forward', 'trace.seekEnd': 'Seek to end', 'trace.instanceEvent': 'instance event',
  'component.loading': 'Loading…', 'component.instanceNotFound': 'Instance not found', 'component.loadingDiagram': 'Loading diagram…', 'component.noDefinition': 'No process definition', 'component.loadingTimeline': 'Loading timeline…', 'component.allTokens': 'All tokens', 'component.allTypes': 'All types', 'component.noEvents': 'No events', 'component.clickEvent': 'Click a timeline item to see details', 'component.eventDetails': 'Event Details', 'component.filterToken': 'Filter by token', 'component.filterType': 'Filter by event type', 'component.engine': 'engine', 'component.database': 'database',
}

const zh: Record<string, string> = {
  'language.label': '语言', 'language.en': 'English', 'language.zh': '中文',
  'shell.tagline': '持久化优先', 'shell.overview': '总览', 'shell.definitions': '流程定义', 'shell.instances': '流程实例', 'shell.tasks': '人工任务', 'shell.workers': 'Worker 实验室', 'shell.deadLetters': '死信队列', 'shell.diagnostics': '运行诊断',
  'shell.online': '引擎在线', 'shell.offline': '引擎离线', 'shell.checking': '正在检查引擎', 'shell.tenant': '租户', 'shell.default': '默认', 'shell.apiKey': 'API 密钥', 'shell.optional': '可选', 'shell.save': '保存连接配置',
  'common.refresh': '刷新', 'common.delete': '删除', 'common.none': '无', 'common.instance': '实例', 'common.token': '令牌', 'common.tenant': '租户', 'common.task': '任务', 'common.status': '状态', 'common.variables': '变量', 'common.required': '必填', 'common.select': '请选择…', 'common.true': '是', 'common.false': '否', 'common.default': '默认',
  'status.active': '活动', 'status.deprecated': '已废弃', 'status.running': '运行中', 'status.completed': '已完成', 'status.terminated': '已终止', 'status.waiting': '等待中', 'status.ready': '就绪', 'status.executing': '执行中', 'status.created': '已创建', 'status.suspended': '已暂停', 'status.ok': '正常', 'status.degraded': '降级', 'status.critical': '严重', 'status.warning': '警告', 'status.info': '信息', 'status.pass': '通过', 'status.fail': '失败',
  'home.eyebrow': '运营控制', 'home.title': '工作流控制台', 'home.description': '在一个控制台中部署、执行、检查和恢复持久化工作流。', 'home.refresh': '刷新数据',
  'home.definitions': '流程定义', 'home.definitionHint': '已部署版本', 'home.instances': '流程实例', 'home.instanceHint': '全部执行记录', 'home.openTasks': '待办任务', 'home.taskHint': '等待处理', 'home.deadLetters': '死信任务', 'home.deadHint': '需要恢复',
  'home.readiness': '运行就绪状态', 'home.readinessHint': '来自引擎的实时组件检查', 'home.serviceState': '当前服务状态', 'home.unknown': '未知', 'home.invariants': '持久化不变量', 'home.invariantsHint': '跨持久化引擎状态的一致性检查', 'home.allPassed': '全部检查通过', 'home.violations': '{count} 个违规项', 'home.validationTime': '检查耗时 {ms} 毫秒', 'home.external': '外部任务',
  'home.quick': '快捷操作', 'home.quickHint': '快速进入常用运营流程', 'home.deploy': '部署 BPMN', 'home.deployHint': '发布不可变的新流程定义。', 'home.start': '启动实例', 'home.startHint': '使用运行变量启动工作流。', 'home.claim': '领取任务', 'home.claimHint': '获取并管理带租约的外部任务。',
  'definitions.eyebrow': '设计注册中心', 'definitions.title': '流程定义', 'definitions.description': '部署 BPMN、管理不可变版本并启动新的执行。', 'definitions.registry': '流程定义注册表', 'definitions.count': '共 {count} 个已部署版本', 'definitions.empty': '暂无流程定义', 'definitions.emptyHint': '请从编辑器部署 BPMN 开始。',
  'definitions.detail': '流程定义详情', 'definitions.select': '选择流程定义', 'definitions.created': '创建于 {date}', 'definitions.deprecate': '废弃', 'definitions.activate': '激活', 'definitions.nothing': '尚未选择', 'definitions.nothingHint': '请从注册表选择一个流程定义。', 'definitions.activeVersion': '活动版本', 'definitions.startNode': '开始节点', 'definitions.nodes': '节点数', 'definitions.edges': '连线数', 'definitions.history': '版本历史', 'definitions.graph': '流程图模型', 'definitions.initialVariables': '初始变量', 'definitions.encrypted': '加密变量名', 'definitions.start': '启动流程实例', 'definitions.deployment': 'BPMN 部署', 'definitions.deploymentHint': '粘贴可执行的 BPMN 2.0 XML；相同 key 会创建版本元数据。', 'definitions.characters': '{count} 个字符', 'definitions.deploy': '部署流程定义', 'definitions.deployed': '已部署 {id}', 'definitions.statusChanged': '{id} 现已设为 {status}',
  'instances.eyebrow': '执行清单', 'instances.title': '流程实例', 'instances.description': '启动工作流、查找执行并打开持久化追踪。', 'instances.startTitle': '启动新实例', 'instances.startHint': '部署后可立即使用活动流程定义。', 'instances.definition': '流程定义', 'instances.start': '启动实例', 'instances.lookup': '精确查找', 'instances.lookupHint': '使用日志或外部系统中的精确实例 ID。', 'instances.id': '实例 ID', 'instances.load': '加载实例', 'instances.inventory': '执行清单', 'instances.matching': '找到 {count} 个实例', 'instances.search': '搜索实例', 'instances.empty': '未找到实例', 'instances.emptyHint': '请启动流程实例或修改搜索条件。', 'instances.definitionColumn': '流程定义', 'instances.currentNodes': '当前节点', 'instances.tokens': '令牌数', 'instances.openTrace': '打开追踪 →',
  'tasks.eyebrow': '人工工作流', 'tasks.title': '任务收件箱', 'tasks.description': '查看生成的表单结构，并使用校验后的变量完成人工任务。', 'tasks.refresh': '刷新收件箱', 'tasks.waiting': '待处理任务', 'tasks.available': '共有 {count} 个任务', 'tasks.empty': '收件箱已清空', 'tasks.emptyHint': '当前没有等待完成的人工任务。', 'tasks.detail': '任务详情', 'tasks.choose': '从收件箱选择任务', 'tasks.noSelection': '尚未选择任务', 'tasks.noSelectionHint': '选择任务以加载其 BPMN 表单结构。', 'tasks.completeTitle': '完成 {node}', 'tasks.formKey': '表单 Key', 'tasks.inlineForm': '内联表单', 'tasks.noFields': '没有结构化表单字段，可使用空变量对象完成任务。', 'tasks.complete': '完成任务', 'tasks.completed': '任务 {id} 已完成',
  'workers.eyebrow': '租约模拟器', 'workers.title': '外部 Worker 实验室', 'workers.description': '无需单独运行 SDK Worker，即可验证 fetch-and-lock 语义并管理任务租约。', 'workers.subscription': 'Worker 订阅', 'workers.subscriptionHint': '按主题使用独占限时租约领取就绪任务。', 'workers.workerId': 'Worker ID', 'workers.topics': '任务主题', 'workers.maxTasks': '最大任务数', 'workers.lockDuration': '锁定时长（毫秒）', 'workers.fetch': '获取并锁定任务', 'workers.leased': '已领取工作', 'workers.owned': '{worker} 已领取 {count} 个任务', 'workers.empty': '暂无已领取任务', 'workers.emptyHint': '按主题获取可用的外部任务。', 'workers.operation': '任务操作', 'workers.select': '选择已领取任务', 'workers.noSelection': '尚未选择任务', 'workers.noSelectionHint': '选择任务以完成、失败或延长租约。', 'workers.completionVariables': '完成变量', 'workers.failureMessage': '失败信息', 'workers.extend': '延长租约', 'workers.fail': '标记失败', 'workers.complete': '完成任务', 'workers.inputVariables': '输入变量', 'workers.locked': '已锁定 {count} 个任务', 'workers.actionResult': '{id}：{action}', 'workers.action.extended': '租约已延长', 'workers.action.completed': '已完成', 'workers.action.failed': '已失败', 'workers.defaultError': 'Worker 报告错误',
  'dead.eyebrow': '恢复队列', 'dead.title': '死信队列', 'dead.description': '检查重试耗尽的外部任务，重新入队可恢复任务或删除过期记录。', 'dead.refresh': '刷新队列', 'dead.failed': '失败任务', 'dead.count': '{count} 个条目需要处理', 'dead.empty': '队列为空', 'dead.emptyHint': '没有外部任务耗尽重试次数。', 'dead.detail': '死信详情', 'dead.select': '选择一个条目', 'dead.requeue': '重新入队', 'dead.noSelection': '尚未选择条目', 'dead.noSelectionHint': '选择死信以检查失败上下文。', 'dead.persistedVariables': '持久化变量', 'dead.requeued': '任务 {id} 已重新入队', 'dead.deleted': '死信已删除', 'dead.confirm': '确定删除死信 {id}？',
  'diagnostics.eyebrow': '运行保障', 'diagnostics.title': '运行诊断', 'diagnostics.description': '探测服务健康状态，并验证引擎执行的持久化形式不变量。', 'diagnostics.run': '运行检查', 'diagnostics.liveness': '存活状态', 'diagnostics.readiness': '就绪状态', 'diagnostics.result': '不变量结果', 'diagnostics.violations': '{count} 个违规项', 'diagnostics.latency': '检查耗时', 'diagnostics.scan': '完整持久化扫描', 'diagnostics.readinessChecks': '就绪检查', 'diagnostics.readinessHint': 'REST 服务报告的组件级可用性', 'diagnostics.entities': '已检查实体', 'diagnostics.entitiesHint': '最近一次不变量扫描范围', 'diagnostics.externalTasks': '外部任务', 'diagnostics.timers': '定时器', 'diagnostics.invariantViolations': '不变量违规项', 'diagnostics.invariantHint': '严重项表示状态损坏，警告项可能影响执行正确性。', 'diagnostics.noViolations': '没有违规项', 'diagnostics.noViolationsHint': '当前所有持久化不变量均成立。', 'diagnostics.severity': '严重程度', 'diagnostics.invariant': '不变量', 'diagnostics.entity': '实体', 'diagnostics.details': '说明',
  'trace.instances': '流程实例', 'trace.missing': '缺少实例 ID。', 'trace.return': '返回实例列表', 'trace.topology': '流程拓扑', 'trace.topologyHint': '编译后流程定义中的当前令牌位置', 'trace.history': '执行历史', 'trace.historyHint': '按因果顺序持久化并支持筛选的事件', 'trace.payload': '事件载荷', 'trace.payloadHint': '选择时间线记录以查看持久化数据', 'trace.replay': '确定性回放', 'trace.replayHint': '在隔离会话中逐事件重建状态', 'trace.createReplay': '创建回放', 'trace.close': '关闭会话', 'trace.timelineCount': '{count} 条令牌时间线', 'trace.createHint': '创建临时回放会话，逐步执行 {count} 个持久化事件。', 'trace.back': '后退', 'trace.step': '单步前进', 'trace.seekEnd': '跳到结尾', 'trace.instanceEvent': '实例事件',
  'component.loading': '加载中…', 'component.instanceNotFound': '未找到实例', 'component.loadingDiagram': '正在加载流程图…', 'component.noDefinition': '没有流程定义', 'component.loadingTimeline': '正在加载时间线…', 'component.allTokens': '全部令牌', 'component.allTypes': '全部类型', 'component.noEvents': '暂无事件', 'component.clickEvent': '点击时间线条目查看详情', 'component.eventDetails': '事件详情', 'component.filterToken': '按令牌筛选', 'component.filterType': '按事件类型筛选', 'component.engine': '引擎', 'component.database': '数据库',
}

const dictionaries = { en, zh }
const STORAGE_KEY = 'bpm-console-locale'

function interpolate(template: string, params: Params = {}) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(params[key] ?? `{${key}}`))
}

interface I18nValue {
  locale: Locale
  setLocale: (locale: Locale) => void
  t: (key: string, params?: Params) => string
  formatDate: (value: string | number | Date) => string
  formatNumber: (value: number) => string
}

const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({ children }: PropsWithChildren) {
  const [locale, setLocaleState] = useState<Locale>(() => localStorage.getItem(STORAGE_KEY) === 'zh' ? 'zh' : 'en')
  const setLocale = (next: Locale) => { localStorage.setItem(STORAGE_KEY, next); setLocaleState(next) }
  useEffect(() => { document.documentElement.lang = locale === 'zh' ? 'zh-CN' : 'en' }, [locale])
  const value = useMemo<I18nValue>(() => ({
    locale,
    setLocale,
    t: (key, params) => interpolate(dictionaries[locale][key] ?? en[key] ?? key, params),
    formatDate: (value) => {
      const normalized = typeof value === 'string' && /^\d+$/.test(value) ? Number(value) * 1000 : value
      return new Intl.DateTimeFormat(locale === 'zh' ? 'zh-CN' : 'en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(normalized))
    },
    formatNumber: (value) => new Intl.NumberFormat(locale === 'zh' ? 'zh-CN' : 'en-US').format(value),
  }), [locale])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used inside I18nProvider')
  return value
}
