[package]
name = "bpm-engine-adapter-memory"
version = "0.2.0"
edition = "2021"
description = "In-memory storage adapter for the BPM engine"
license = "MIT"

[dependencies]
bpm-engine-core = { path = "../../core", version = "0.2.0" }
bpm-engine-storage = { path = "../../storage", version = "0.2.0" }
anyhow = { workspace = true }
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
uuid = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
