[package]
name = "bpm-engine-adapter-postgres"
version = "0.2.0"
edition = "2021"
description = "PostgreSQL adapter for the BPM engine"
license = "MIT"

[dependencies]
bpm-engine-core = { path = "../../core", version = "0.2.0" }
bpm-engine-storage = { path = "../../storage", version = "0.2.0" }

anyhow = { workspace = true }
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
deadpool-postgres = "0.12"
uuid = { version = "1", features = ["v4", "serde"] }
url = "2"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
